# intelliflash-csi-block-driver config file to create k8s secret
#
# $ kubectl create secret generic intelliflash-csi-block-driver-config \
#   --from-file=deploy/kubernetes/intelliflash-csi-block-driver-config.yaml
#
arrays:
  array1:
    restIp: https://10.204.86.70:443
    username: admin
    password: t
    defaultProject: csi-block-test1
    defaultDataIp: 10.204.86.71
    zone: zone-1
  array2:
    restIp: https://10.204.86.70:443
    username: admin
    password: t
    defaultProject: csi-block-test2
    defaultDataIp: 10.204.86.75
    zone: zone-2
debug: true